"""
Write the SQL that loads the harness test data into the TDEI content tables.

    python3 harness/load_test_data.py > runs/load_test_data.sql
    psql "$PGCONN" -v ON_ERROR_STOP=1 -f runs/load_test_data.sql

Loads DS1 as dataset id 'harness-ds1' and DS2 as 'harness-ds2' (change with
--ds1-id / --ds2-id). Rows already under those ids are deleted first, so it is
safe to re-run after regenerating the data. Nothing else in the tables is touched.

Matches the real TDEI tables: only (tdei_dataset_id, feature) are inserted —
ids, geometry and tag columns are GENERATED from the feature. Use a dev
database or the local Docker one (docker-compose.yml), not production.
"""
import argparse, json, os

DATA = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
ap = argparse.ArgumentParser()
ap.add_argument("--ds1-id", default="harness-ds1")
ap.add_argument("--ds2-id", default="harness-ds2")
args = ap.parse_args()

def q(s): return "'" + str(s).replace("'", "''") + "'"
def feats(name): return json.load(open(os.path.join(DATA, name)))["features"]

print("-- generated by load_test_data.py\n\\set ON_ERROR_STOP on\nBEGIN;")
for ds_id in (args.ds1_id, args.ds2_id):
    print(f"DELETE FROM content.node WHERE tdei_dataset_id = {q(ds_id)};")
    print(f"DELETE FROM content.edge WHERE tdei_dataset_id = {q(ds_id)};")
for ds, ds_id in (("ds1", args.ds1_id), ("ds2", args.ds2_id)):
    for table, kind in (("node", "nodes"), ("edge", "edges")):
        for f in feats(f"{ds}_{kind}.geojson"):
            print(f"INSERT INTO content.{table} (tdei_dataset_id, feature) VALUES "
                  f"({q(ds_id)}, {q(json.dumps(f))}::json);")
print("COMMIT;")
print("SELECT 'node' AS entity, tdei_dataset_id, COUNT(*) FROM content.node "
      f"WHERE tdei_dataset_id IN ({q(args.ds1_id)}, {q(args.ds2_id)}) GROUP BY 1, 2 "
      "UNION ALL SELECT 'edge', tdei_dataset_id, COUNT(*) FROM content.edge "
      f"WHERE tdei_dataset_id IN ({q(args.ds1_id)}, {q(args.ds2_id)}) GROUP BY 1, 2 ORDER BY 1, 2;")
